exports.countryOptions = [
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Antigua và Barbuda", label: "Antigua và Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Úc", label: "Úc" },
    { value: "Áo", label: "Áo" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Bỉ", label: "Bỉ" },
    { value: "Belize", label: "Belize" },
    { value: "Bénin", label: "Bénin" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia và Herzegovina", label: "Bosnia và Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazil" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cabo Verde", label: "Cabo Verde" },
    { value: "Campuchia", label: "Campuchia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Canada", label: "Canada" },
    { value: "Cộng hòa Trung Phi", label: "Cộng hòa Trung Phi" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "Trung Quốc", label: "Trung Quốc" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoros", label: "Comoros" },
    { value: "Congo", label: "Congo" },
    { value: "Congo (Cộng hòa Dân chủ)", label: "Congo (Cộng hòa Dân chủ)" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Croatia", label: "Croatia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Síp", label: "Síp" },
    { value: "Séc", label: "Séc" },
    { value: "Đan Mạch", label: "Đan Mạch" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Cộng hòa Dominica", label: "Cộng hòa Dominica" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Ai Cập", label: "Ai Cập" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Guinea Xích Đạo", label: "Guinea Xích Đạo" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Eswatini", label: "Eswatini" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Fiji", label: "Fiji" },
    { value: "Phần Lan", label: "Phần Lan" },
    { value: "Pháp", label: "Pháp" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Gruzia", label: "Gruzia" },
    { value: "Đức", label: "Đức" },
    { value: "Ghana", label: "Ghana" },
    { value: "Hy Lạp", label: "Hy Lạp" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "Ấn Độ", label: "Ấn Độ" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Ireland", label: "Ireland" },
    { value: "Israel", label: "Israel" },
    { value: "Ý", label: "Ý" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Nhật Bản", label: "Nhật Bản" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Triều Tiên", label: "Triều Tiên" },
    { value: "Hàn Quốc", label: "Hàn Quốc" },
    { value: "Kosovo", label: "Kosovo" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Lào", label: "Lào" },
    { value: "Latvia", label: "Latvia" },
    { value: "Li-băng", label: "Li-băng" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Litva", label: "Litva" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Quần đảo Marshall", label: "Quần đảo Marshall" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mexico", label: "Mexico" },
    { value: "Liên bang Micronesia", label: "Liên bang Micronesia" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mông Cổ", label: "Mông Cổ" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Ma-rốc", label: "Ma-rốc" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Hà Lan", label: "Hà Lan" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Bắc Macedonia", label: "Bắc Macedonia" },
    { value: "Na Uy", label: "Na Uy" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Ba Lan", label: "Ba Lan" },
    { value: "Bồ Đào Nha", label: "Bồ Đào Nha" },
    { value: "Qatar", label: "Qatar" },
    { value: "Romania", label: "Romania" },
    { value: "Nga", label: "Nga" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint Kitts và Nevis", label: "Saint Kitts và Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    { value: "Saint Vincent và Grenadines", label: "Saint Vincent và Grenadines" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Sao Tome và Principe", label: "Sao Tome và Principe" },
    { value: "Ả Rập Xê-út", label: "Ả Rập Xê-út" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Quần đảo Solomon", label: "Quần đảo Solomon" },
    { value: "Somalia", label: "Somalia" },
    { value: "Nam Phi", label: "Nam Phi" },
    { value: "Nam Sudan", label: "Nam Sudan" },
    { value: "Tây Ban Nha", label: "Tây Ban Nha" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Thụy Điển", label: "Thụy Điển" },
    { value: "Thụy Sĩ", label: "Thụy Sĩ" },
    { value: "Syria", label: "Syria" },
    { value: "Đài Loan", label: "Đài Loan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thái Lan", label: "Thái Lan" },
    { value: "Đông Timor", label: "Đông Timor" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad và Tobago", label: "Trinidad và Tobago" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Thổ Nhĩ Kỳ", label: "Thổ Nhĩ Kỳ" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "Các Tiểu vương quốc Ả Rập Thống nhất", label: "Các Tiểu vương quốc Ả Rập Thống nhất" },
    { value: "Vương quốc Anh", label: "Vương quốc Anh" },
    { value: "Hoa Kỳ", label: "Hoa Kỳ" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Vatican", label: "Vatican" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Việt Nam", label: "Việt Nam" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
];

exports.yearOptions = [
    { value: 2024, label: 2024 },
    { value: 2023, label: 2023 },
    { value: 2022, label: 2022 },
    { value: 2021, label: 2021 },
    { value: 2020, label: 2020 },
    { value: 2019, label: 2019 },
    { value: 2018, label: 2018 },
    { value: 2017, label: 2017 },
    { value: 2016, label: 2016 },
    { value: 2015, label: 2015 },
    { value: 2014, label: 2014 },
    { value: 2013, label: 2013 },
    { value: 2012, label: 2012 },
    { value: 2011, label: 2011 },
    { value: 2010, label: 2010 },
    { value: 2009, label: 2009 },
    { value: 2008, label: 2008 },
    { value: 2007, label: 2007 },
    { value: 2006, label: 2006 },
    { value: 2005, label: 2005 },
    { value: 2004, label: 2004 },
    { value: 2003, label: 2003 },
    { value: 2002, label: 2002 },
    { value: 2001, label: 2001 },
    { value: 2000, label: 2000 },
    { value: 1999, label: 1999 },
    { value: 1998, label: 1998 },
    { value: 1997, label: 1997 },
    { value: 1996, label: 1996 },
    { value: 1995, label: 1995 },
    { value: 1994, label: 1994 },
    { value: 1993, label: 1993 },
    { value: 1992, label: 1992 },
    { value: 1991, label: 1991 },
    { value: 1990, label: 1990 },
    { value: 1989, label: 1989 },
    { value: 1988, label: 1988 },
    { value: 1987, label: 1987 },
    { value: 1986, label: 1986 },
    { value: 1985, label: 1985 },
    { value: 1984, label: 1984 },
    { value: 1983, label: 1983 },
    { value: 1982, label: 1982 },
    { value: 1981, label: 1981 },
    { value: 1980, label: 1980 },
];
